version: '3.8'

services:
  database:
    image: postgres:14.1-alpine
    container_name: tailpool-pg-database
    restart: always
    ports:
      - ${PG_PORT}:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=tailpooldb
    volumes:
      - pgdata:/data/postgres
    network_mode: host

volumes:
  pgdata:
